# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Travis continuous integration system configuration file.
#
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

dist: trusty
sudo: required

# Cache downloaded Node.JS modules & Bower frontend dependencies for faster builds.
cache:
  directories:
    - node_modules
    - bower_components
    - .tools

# Use Node.js as primary language because Gulp is the build system used in the project.
language: node_js
node_js:
  - 5.1.1

# Docker is required to set up a simple, single node Kubernetes cluster.
# Local Docker-based cluster is the simplest way to create kubernetes on the host machine.
services:
  - docker

env:
  global:
  - SAUCE_USERNAME=k8s-dashboard-ci

matrix:
  include:
      # Job 1 - Local cluster + integration tests
      - env: BUILD_SUITE=cluster_test
        addons:
          # Run tests that require a browser on SauceLabs CI provider. Learn more at: https://saucelabs.com
          sauce_connect: true
          jwt:
            secure: THjUBgOJsT45z9Goy7UTjQ+4yvcO4XP2ghd40Q8HXro6MEh5X/DKx/J5LVgDtKaYj/XDto9gWPxlvFK2aEqnmtJkbrGiqTvJX6Lt8o3x0dhcvsrB6XYOLadKDpXq5nQ50idW1W1IoWFk7lNGugxsFY383hziCijU1qbrEc523FVRRvRhGWVmwMySGi50kvU1ez9PyPpF1ljd4A+VUI3DuW/KxvguDewGCsHP9pxBLIzkMeklze4etAeUaF2njBB+0BS6o9rYWncJ0I2i82zZVXEXsvN+ICoRzRcz0Exbxe46xHt/EwgyYGac600UnBxjQt+rVibv+0J7RxYexUfLq74xiiEqT7w+/WLTSMUUTmyOrgl/JvOAeEBhAShcQZ/2ky1tnem4TkT9XAI14vvZVKgWjmRT/rY4nOvZAWwjI9WBrRHcAM8aE+QDvPiuMZE7dXAO8RGWmr9dCiZO8G1VOtDk0okJU57u4PDT3qx0xrR3FBPAGjkTpmfDvSKl7ijV4WN6mOrxWp5dQFvYibQt1jeUcyhmNdW4E+eNd9Ze9R+mqMq1IM5LsLnrMpx8+cCMuLProLgU8SJFznfzhAGKm/w37Xi10nzfwqpAfiZQvRmMM2brt9U0uUwfm2afyoCXIkpiHJSwuqV7eMDAUx4cDG9MNadqRPLhsgrSNyjEScE=
      # Job 2 - Run only code tests, frontend + backend
      - env: BUILD_SUITE=code_test

before_script:
  # Install go 1.7.1. It is not there by default.
  - eval "$(gimme 1.7.1)"
  - docker --version

script:
  - 'if [ BUILD_SUITE = "cluster_test" ]; then
      ./node_modules/.bin/gulp ci --heapsterServerHost http://localhost:8082;
    else
      ./node_modules/.bin/gulp test;
    fi'

after_script:
  - 'if [ BUILD_SUITE = "code_test" ]; then
      ./node_modules/.bin/gulp coverage-codecov-upload;
    fi'
